# Generated by Django 2.2.5 on 2019-09-15 18:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('state_of_origin', models.CharField(default='', max_length=20)),
                ('age', models.IntegerField(default=0)),
                ('phone_no', models.IntegerField(default=0)),
                ('address', models.CharField(default='', max_length=100)),
                ('gender', models.CharField(choices=[('m', 'Male'), ('f', 'Female')], default='', max_length=100)),
                ('status', models.CharField(choices=[('p', 'Passed-Out'), ('c', 'Corper')], default='', max_length=100)),
                ('office', models.CharField(choices=[('t', 'Treasurer'), ('es', 'Evangelism secretary'), ('a', 'As. Welfare'), ('n', 'NIL'), ('pro', 'PRO'), ('bs', 'Bible study secretary'), ('as/f', 'Ass Secretary/Fin sec'), ('s', 'Secretary'), ('md', 'Music Director.'), ('aes', 'Ass Evangelism sec'), ('p', 'President'), ('ws', 'Welfare secretary'), ('vp', 'Vice-president'), ('ss', 'Sisters cod')], default='', max_length=100)),
                ('qualification', models.CharField(default='', max_length=100)),
                ('state_code', models.CharField(default='', max_length=20)),
                ('ppa', models.CharField(default='', max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
