# Generated by Django 2.2.5 on 2019-09-15 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190915_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='office',
            field=models.CharField(choices=[('as/f', 'Ass Secretary/Fin sec'), ('aes', 'Ass Evangelism sec'), ('a', 'As. Welfare'), ('pro', 'PRO'), ('md', 'Music Director.'), ('p', 'President'), ('s', 'Secretary'), ('ss', 'Sisters cod'), ('t', 'Treasurer'), ('bs', 'Bible study secretary'), ('es', 'Evangelism secretary'), ('n', 'NIL'), ('ws', 'Welfare secretary'), ('vp', 'Vice-president')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.CharField(choices=[('p', 'Passed-Out'), ('c', 'Corper')], default='', max_length=100),
        ),
    ]
