# Generated by Django 2.2.5 on 2019-09-15 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190915_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='office',
            field=models.CharField(choices=[('bs', 'Bible study secretary'), ('pro', 'PRO'), ('ws', 'Welfare secretary'), ('es', 'Evangelism secretary'), ('md', 'Music Director.'), ('ss', 'Sisters cod'), ('n', 'NIL'), ('t', 'Treasurer'), ('a', 'As. Welfare'), ('p', 'President'), ('vp', 'Vice-president'), ('aes', 'Ass Evangelism sec'), ('as/f', 'Ass Secretary/Fin sec'), ('s', 'Secretary')], default='', max_length=100),
        ),
    ]
