# Generated by Django 2.2.5 on 2019-09-27 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190916_0013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='office',
            field=models.CharField(choices=[('md', 'Music Director.'), ('ss', 'Sisters cod'), ('t', 'Treasurer'), ('p', 'President'), ('bs', 'Bible study secretary'), ('n', 'NIL'), ('s', 'Secretary'), ('es', 'Evangelism secretary'), ('aes', 'Ass Evangelism sec'), ('vp', 'Vice-president'), ('as/f', 'Ass Secretary/Fin sec'), ('ws', 'Welfare secretary'), ('pro', 'PRO'), ('a', 'As. Welfare')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_no',
            field=models.BigIntegerField(default=0),
        ),
    ]
