# Generated by Django 2.2.5 on 2019-09-27 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20190927_0837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='office',
            field=models.CharField(choices=[('a', 'As. Welfare'), ('aes', 'Ass Evangelism sec'), ('es', 'Evangelism secretary'), ('t', 'Treasurer'), ('as/f', 'Ass Secretary/Fin sec'), ('md', 'Music Director.'), ('vp', 'Vice-president'), ('ss', 'Sisters cod'), ('p', 'President'), ('bs', 'Bible study secretary'), ('s', 'Secretary'), ('pro', 'PRO'), ('ws', 'Welfare secretary'), ('n', 'NIL')], default='', max_length=100),
        ),
    ]
